### ISSUE TITLE
Getting Error on ESP8266

### ISSUE THREAD

**Issue by bkrajendra** [Toshik/TickerScheduler#21] opened 2019-11-14 09:36 UTC
Earlier was working fine,
But recently after some esp core arduino sdk update, its throwing error:

```
In file included from C:\Users\Rajendra\Documents\Arduino\libraries\TickerScheduler-master\TickerScheduler.h:47:0,

                 from C:\Users\Rajendra\Documents\Arduino\libraries\TickerScheduler-master\TickerScheduler.cpp:1:

C:\Users\Rajendra\Documents\Arduino\hardware\esp8266com\esp8266\libraries\Ticker/Ticker.h: In instantiation of 'void Ticker::attach_ms(uint32_t, void (*)(TArg), TArg) [with TArg = volatile bool*; uint32_t = unsigned int]':

C:\Users\Rajendra\Documents\Arduino\libraries\TickerScheduler-master\TickerScheduler.cpp:85:91:   required from here

C:\Users\Rajendra\Documents\Arduino\hardware\esp8266com\esp8266\libraries\Ticker/Ticker.h:74:112: error: reinterpret_cast from type 'volatile bool*' to type 'void*' casts away qualifiers

   _attach_ms(milliseconds, true, reinterpret_cast<callback_with_arg_t>(callback), reinterpret_cast<void *>(arg));
```
                                                                                                                ^

**Comment by bozont** [comment] 2019-11-19 22:09
Hello!
I can confirm it also, I'm getting the same compilation error.
Here's the breaking change in the underlying Ticker library: https://github.com/esp8266/Arduino/pull/6496/commits/a833f270af61904700dd0c0492b53b1d53026ef1

**Comment by bkrajendra** [comment] 2020-01-27 12:52
temporarily i resolve it by changing those changes back to earlier what it was.
Thank you @bozont 

```
_attach_ms(milliseconds, true, reinterpret_cast<callback_with_arg_t>(callback), reinterpret_cast<void*>(arg));
```
to
```
_attach_ms(milliseconds, true, reinterpret_cast<callback_with_arg_t>(callback), (void*)arg);

```

**Comment by bkrajendra** [comment] 2020-01-27 17:45
@Toshik please take a note of this:
https://github.com/esp8266/Arduino/commit/a833f270af61904700dd0c0492b53b1d53026ef1#commitcomment-36981777

**Comment by bozont** [comment] 2020-01-27 18:57
Hello @bkrajendra !
Thanks for doing some further investigation! I solved the problem the same way as you were suggested in the esp8266/Arduino thread - by removing the `volatile` qualifier. For me it's been working steady since I made my previous comment. I can make a pull request from my changes, and if @Toshik agrees, it can be merged easily.

**Comment by dakky** [comment] 2020-05-03 21:41
@Toshik any plans to merge this PR?

**Comment by mmv-ru** [comment] 2020-06-11 00:05
https://github.com/Toshik/TickerScheduler/compare/master...flavio-fernandes:esp8266.no.volatile
Look same but more complete

**Comment by mmv-ru** [comment] 2020-06-11 00:07
Look like last compatible version of ESP8266 platform is 2.5.2

**Comment by 45gfg9** [comment] 2020-07-09 05:09
Ahh, compile error on macOS also

**Comment by Toshik** [comment] 2020-07-09 20:41
Should be fixed by https://github.com/Toshik/TickerScheduler/commit/a2b434752c33f389738dd602cf21ea3302f45275

**Closed as completed by Toshik** 2020-07-09 20:41 UTC
